In [1]:
import pandas as pd

df = pd.read_excel("Pasta1.xlsx")
df.head()

DADOS_PESSOAIS: NOME DADOS_PESSOAIS: SEXO  \
0               Vanessa Lopes             Feminino   
1          Jose Ariel Machado            Masculino   
2      Jociane Bulegon Samara             Feminino   
3  Sabrina Dalla Costa Saurim             Feminino   
4  Patricia machado inchauspe             Feminino   

  DADOS_PESSOAIS: FAIXA_ETARIA DADOS_PESSOAIS: POSICAO_QUADRA  \
0           Entre 36 e 45 anos                        Direita   
1           Entre 36 e 45 anos                       Esquerda   
2           Entre 46 e 55 anos                       Esquerda   
3           Entre 36 e 45 anos                       Esquerda   
4           Entre 46 e 55 anos                        Direita   

  EXPERIENCIA: TEMPO_PADEL EXPERIENCIA: QUANTIDADE_TREINOS  \
0         Entre 3 e 5 anos                      Não treino   
1         Entre 3 e 5 anos                      Não treino   
2         Entre 3 e 5 anos                1 vez por semana   
3               Até 2 anos                1 vez por semana   
4          Mais de 11 anos                      Não treino   

  EXPERIENCIA: QUANTIDADE_JOGOS EXPERIENCIA: PARTICIPA_TORNEIOS  \
0            3 vezes por semana                             Sim   
1            3 vezes por semana                             Sim   
2              1 vez por semana                             Sim   
3            2 vezes por semana                             Sim   
4              1 vez por semana                             Sim   

  EXPERIENCIA: CATEGORIA_EM_TORNEIOS  HABILIDADE_TECNICA: SAQUE  ...  \
0                       4ª categoria                          3  ...   
1                       2ª categoria                          4  ...   
2                       4ª categoria                          3  ...   
3                       4ª categoria                          3  ...   
4                       4ª categoria                          4  ...   

              COMPOSICAO_JOGO: BANDEJA_RETOMADA_REDE  \
0  Minha bandeja é regular e me ajuda a manter o ...   
1  Minha bandeja é regular e me ajuda a manter o ...   
2  Consigo acertar a bandeja, mas com pouca profu...   
3  Minha bandeja é regular e me ajuda a manter o ...   
4  Minha bandeja é regular e me ajuda a manter o ...   

                              COMPOSICAO_JOGO: SMASH  \
0  Consigo acertar smashes simples, mas sem final...   
1  Tenho boa potência e controle no smash, especi...   
2  Consigo acertar smashes simples, mas sem final...   
3  Consigo acertar smashes simples, mas sem final...   
4  Tenho boa potência e controle no smash, especi...   

          COMPOSICAO_JOGO: TROCA_BOLA_FUNDO_FOREHAND  \
0  Tenho regularidade nos golpes de fundo, com bo...   
1  Tenho regularidade nos golpes de fundo, com bo...   
2  Consigo manter trocas de bola, mas com pouca p...   
3  Sou consistente e uso os golpes de fundo para ...   
4  Tenho regularidade nos golpes de fundo, com bo...   

          COMPOSICAO_JOGO: TROCA_BOLA_FUNDO_BACKHAND  \
0  Tenho regularidade nos golpes de fundo, com bo...   
1  Consigo manter trocas de bola, mas com pouca p...   
2  Consigo manter trocas de bola, mas com pouca p...   
3  Sou consistente e uso os golpes de fundo para ...   
4  Tenho regularidade nos golpes de fundo, com bo...   

                    COMPOSICAO_JOGO: DEVOLUCAO_SAQUE  \
0  Minhas devoluções são regulares e dificultam o...   
1  Minhas devoluções são regulares e dificultam o...   
2     Consigo devolver, mas sem colocação ou efeito.   
3  Sou capaz de devolver saques com precisão e in...   
4  Minhas devoluções são regulares e dificultam o...   

                COMPOSICAO_JOGO: SAIDA_PAREDE_DEFESA  \
0  Sou consistente nas saídas de parede, com boa ...   
1  Sou consistente nas saídas de parede, com boa ...   
2  Acerto saídas simples, mas sem muita profundid...   
3  Transformo saídas de parede em golpes estratég...   
4  Sou consistente nas saídas de parede, com boa ...   

                 COMPOSICAO_JOGO:SAIDA_PAREDE_ATAQUE  \
0     

In [2]:
#ver linhas x colunas
df.shape

(178, 33)

In [3]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 33 columns):
 #   Column                                      Non-Null Count  Dtype 
---  ------                                      --------------  ----- 
 0   DADOS_PESSOAIS: NOME                        178 non-null    object
 1   DADOS_PESSOAIS: SEXO                        178 non-null    object
 2   DADOS_PESSOAIS: FAIXA_ETARIA                178 non-null    object
 3   DADOS_PESSOAIS: POSICAO_QUADRA              178 non-null    object
 4   EXPERIENCIA: TEMPO_PADEL                    178 non-null    object
 5   EXPERIENCIA: QUANTIDADE_TREINOS             178 non-null    object
 6   EXPERIENCIA: QUANTIDADE_JOGOS               178 non-null    object
 7   EXPERIENCIA: PARTICIPA_TORNEIOS             178 non-null    object
 8   EXPERIENCIA: CATEGORIA_EM_TORNEIOS          178 non-null    object
 9   HABILIDADE_TECNICA: SAQUE                   178 non-null    int64 
 10  HABILIDADE_TECNICA: VOLEIO

In [4]:
df.describe(include="all")


DADOS_PESSOAIS: NOME DADOS_PESSOAIS: SEXO DADOS_PESSOAIS: FAIXA_ETARIA  \
count                   178                  178                          178   
unique                  178                    2                            6   
top           Vanessa Lopes            Masculino           Entre 36 e 45 anos   
freq                      1                  118                           77   
mean                    NaN                  NaN                          NaN   
std                     NaN                  NaN                          NaN   
min                     NaN                  NaN                          NaN   
25%                     NaN                  NaN                          NaN   
50%                     NaN                  NaN                          NaN   
75%                     NaN                  NaN                          NaN   
max                     NaN                  NaN                          NaN   

       DADOS_PESSOAIS: POSICAO_QUADRA EXPERIENCIA: TEMPO_PADEL  \
count                             178                      178   
unique                              4                        5   
top                           Direita               Até 2 anos   
freq                               86                       70   
mean                              NaN                      NaN   
std                               NaN                      NaN   
min                               NaN                      NaN   
25%                               NaN                      NaN   
50%                               NaN                      NaN   
75%                               NaN                      NaN   
max                               NaN                      NaN   

       EXPERIENCIA: QUANTIDADE_TREINOS EXPERIENCIA: QUANTIDADE_JOGOS  \
count                              178                           178   
unique                               5                             4   
top                   1 vez por semana            2 vezes por semana   
freq                                85                            71   
mean                               NaN                           NaN   
std                                NaN                           NaN   
min                                NaN                           NaN   
25%                                NaN                           NaN   
50%                                NaN                           NaN   
75%                                NaN                           NaN   
max                                NaN                           NaN   

       EXPERIENCIA: PARTICIPA_TORNEIOS EXPERIENCIA: CATEGORIA_EM_TORNEIOS  \
count                              178                                178   
unique                               2                                  8   
top                                Sim                       4ª categoria   
freq                               166                                 53   
mean                               NaN                                NaN   
std                                NaN                                NaN   
min                                NaN                                NaN   
25%                                NaN                                NaN   
50%                                NaN                                NaN   
75%                                NaN                                NaN   
max                                NaN                                NaN   

        HABILIDADE_TECNICA: SAQUE  ...  \
count                  178.000000  ...   
unique                        NaN  ...   
top                           NaN  ...   
freq                          NaN  ...   
mean                     3.185393  ...   
std                      0.812619  ...   
min                      1.000000  ...   
25%                      3.000000  ...   
50%                      3.000000  ...   
75%                      4.0000

In [5]:
# verificar quantos valores possuem nulos
df.isnull().sum()


DADOS_PESSOAIS: NOME                           0
DADOS_PESSOAIS: SEXO                           0
DADOS_PESSOAIS: FAIXA_ETARIA                   0
DADOS_PESSOAIS: POSICAO_QUADRA                 0
EXPERIENCIA: TEMPO_PADEL                       0
EXPERIENCIA: QUANTIDADE_TREINOS                0
EXPERIENCIA: QUANTIDADE_JOGOS                  0
EXPERIENCIA: PARTICIPA_TORNEIOS                0
EXPERIENCIA: CATEGORIA_EM_TORNEIOS             0
HABILIDADE_TECNICA: SAQUE                      0
HABILIDADE_TECNICA: VOLEIO                     0
HABILIDADE_TECNICA: SMASH                      0
HABILIDADE_TECNICA: MOVIMENTACAO               0
COMPOSICAO_JOGO: DEFESA_ATAQUE                 0
COMPOSICAO_JOG0: CONTROLE_RITMO                0
OBJETIVO: ESTILO_DUPLAS                        0
OBJETIVO: FOCO                                 0
AUTOAVALIACAO: CATEGORIA                       0
AUTOAVALIACAO: QUALIDADE_CATEGORIA             0
COMPOSICAO_JOGO: SAQUE                         0
COMPOSICAO_JOGO: USA_RETOQUE                   0
COMPOSICAO_JOGO: VOLEIO_ATAQUE                 0
COMPOSICAO_JOGO: VOLEIO_DEFESA_CONTENSAO       0
COMPOSICAO_JOGO: BANDEJA_RETOMADA_REDE         0
COMPOSICAO_JOGO: SMASH                         0
COMPOSICAO_JOGO: TROCA_BOLA_FUNDO_FOREHAND     0
COMPOSICAO_JOGO: TROCA_BOLA_FUNDO_BACKHAND     0
COMPOSICAO_JOGO: DEVOLUCAO_SAQUE               0
COMPOSICAO_JOGO: SAIDA_PAREDE_DEFESA           0
COMPOSICAO_JOGO:SAIDA_PAREDE_ATAQUE            0
COMPOSICAO_JOGO: MOVIMENTACAO                  0
COMPOSICAO_JOGO: POSICIONAMENTO                0
DADOS_PESSOAIS: AUTORIZACAO                   63
dtype: int64

In [6]:
# definir valor nos dados Null
# ATENÇÃO: Apenas a coluna AUTORIZACAO estava com 63 valores NaN. Setei os NaN para SIM
df = df.fillna("Sim")


In [7]:
#verifica se possui algum dado duplicado
df.duplicated().any()


np.False_

In [8]:
# padronizar nomes das colunas
df.columns = df.columns.str.strip().str.lower()

# selecionar apenas colunas do tipo object (texto)
texto_cols = df.select_dtypes(include='object').columns

# aplicar strip + lower apenas nas colunas de texto
df[texto_cols] = df[texto_cols].apply(lambda col: col.str.strip().str.lower())



In [9]:
df = df.rename(columns={
    "composicao_jogo:saida_parede_ataque": "composicao_jogo: saida_parede_ataque"
})

In [10]:
# verificar quantos valores possuem nulos
df.isnull().sum()

dados_pessoais: nome                          0
dados_pessoais: sexo                          0
dados_pessoais: faixa_etaria                  0
dados_pessoais: posicao_quadra                0
experiencia: tempo_padel                      0
experiencia: quantidade_treinos               0
experiencia: quantidade_jogos                 0
experiencia: participa_torneios               0
experiencia: categoria_em_torneios            0
habilidade_tecnica: saque                     0
habilidade_tecnica: voleio                    0
habilidade_tecnica: smash                     0
habilidade_tecnica: movimentacao              0
composicao_jogo: defesa_ataque                0
composicao_jog0: controle_ritmo               0
objetivo: estilo_duplas                       0
objetivo: foco                                0
autoavaliacao: categoria                      0
autoavaliacao: qualidade_categoria            0
composicao_jogo: saque                        0
composicao_jogo: usa_retoque                  0
composicao_jogo: voleio_ataque                0
composicao_jogo: voleio_defesa_contensao      0
composicao_jogo: bandeja_retomada_rede        0
composicao_jogo: smash                        0
composicao_jogo: troca_bola_fundo_forehand    0
composicao_jogo: troca_bola_fundo_backhand    0
composicao_jogo: devolucao_saque              0
composicao_jogo: saida_parede_defesa          0
composicao_jogo: saida_parede_ataque          0
composicao_jogo: movimentacao                 0
composicao_jogo: posicionamento               0
dados_pessoais: autorizacao                   0
dtype: int64

In [11]:
for col in df.columns:
    print(f"Coluna: {col}")
    print(df[col].value_counts())
    print("-" * 40)


Coluna: dados_pessoais: nome
dados_pessoais: nome
vanessa lopes                  1
jose ariel machado             1
jociane bulegon samara         1
sabrina dalla costa saurim     1
patricia machado inchauspe     1
                              ..
luciano pereira                1
letícia pires porto ribeiro    1
fabiano cadore                 1
rafael dessuy haag             1
roberto maurer da silva        1
Name: count, Length: 178, dtype: int64
----------------------------------------
Coluna: dados_pessoais: sexo
dados_pessoais: sexo
masculino    118
feminino      60
Name: count, dtype: int64
----------------------------------------
Coluna: dados_pessoais: faixa_etaria
dados_pessoais: faixa_etaria
entre 36 e 45 anos    77
entre 22 e 35 anos    64
entre 46 e 55 anos    25
entre 18 e 21 anos     6
acima de 55 anos       5
entre 15 e 17 anos     1
Name: count, dtype: int64
----------------------------------------
Coluna: dados_pessoais: posicao_quadra
dados_pessoais: posicao_quadra
dir

In [12]:
# verificando os valores unicos por coluna (importante para fazer o mapeamento)
for col in df.columns:
    print(col, df[col].unique())



dados_pessoais: nome ['vanessa lopes' 'jose ariel machado' 'jociane bulegon samara'
 'sabrina dalla costa saurim' 'patricia machado inchauspe'
 'lorenzo iop laporta' 'carlos eduardo reverbel de souza' 'pedro alves'
 'carolina vieira' 'ricardo giuliani martini' 'andré morgental weber'
 'lorenzo sartori rizzatti' 'ykaraíma moraes da costa caetano'
 'marcos hahn' 'andré pivetta' 'manoel caetano dorneles nogueira'
 'caroline martins machado' 'igor cantarelli' 'ricardo ferreira schroder'
 'gustavo boschin' 'thalles de almeida' 'gleiane ruviaro'
 'marcus vinícius real perini' 'juliana de almeida surdo'
 'carlos augusto de moura alves' 'felipe de andrades knackfuss'
 'juliana corrêa soares' 'jonatan saraiva de abreu' 'lucas felipe zucatto'
 'mario couto' 'diogo vieira de mello' 'paulo lima' 'eggres'
 'juliana vargas' 'tatiane de oliveira pinto' 'gabriel biasuz trevisan'
 'gabriela curto saldanha' 'jamille farias hoffmann' 'guido ruviâro'
 'ronier pauletto gutierrez' 'igor rocha monteiro'
 'gi

In [13]:
# fazendo o dicionário/mapeamento das colunas que possuem textos
# ordem de natural de 1 = fraco até 5 = forte
# Colunas de habilidade técnica

# COMPOSICAO_JOGO: SAQUE
mapa_saque = {
    "raramente consigo acertar o saque em áreas estratégicas.": 1,
    "consigo acertar o saque com regularidade, mas sem muito controle ou potência.": 2,
    "meu saque é consistente, consigo variar entre potência e colocação.": 3,
    "consigo sacar estrategicamente, pressionando o adversário.": 4
}

# COMPOSICAO_JOGO: USA_RETOQUE
mapa_retoque = {
    "não.": 1,
    "sim, mas com dificuldade em manter a qualidade.": 2,
    "sim, e geralmente consigo preparar o ponto com ele.": 3,
    "sim, e uso o retoque como parte fundamental da construção do ponto.": 4
}

# COMPOSICAO_JOGO: VOLEIO_ATAQUE
mapa_voleio_ataque = {
    "acerto voleios simples, mas tenho dificuldade em pressionar o adversário.": 1,
    "consigo executar voleios sólidos com boa colocação.": 2,
    "muitas vezes eu erro a direção ou intensidade.": 3,
    "meus voleios são consistentes e coloco pressão no adversário.": 4
}

# COMPOSICAO_JOGO: VOLEIO_DEFESA_CONTENSAO
mapa_voleio_defesa = {
    "tenho dificuldade em devolver bolas rápidas ou com efeito.": 1,
    "acerto voleios defensivos básicos, mas com pouca profundidade ou controle.": 2,
    "tenho boa técnica para defender voleios e manter a bola em jogo.": 3,
    "sou capaz de transformar a defesa em ataque nos voleios.": 4
}

# COMPOSICAO_JOGO: BANDEJA_RETOMADA_REDE
mapa_bandeja = {
    "tenho dificuldade em executar a bandeja com controle.": 1,
    "consigo acertar a bandeja, mas com pouca profundidade.": 2,
    "minha bandeja é regular e me ajuda a manter o ponto.": 3,
    "uso a bandeja para controlar o ponto e pressionar o adversário.": 4
}

# COMPOSICAO_JOGO: SMASH
mapa_smash = {
    "dificuldade em acertar o smash com potência e controle.": 1,
    "consigo acertar smashes simples, mas sem finalizações efetivas.": 2,
    "tenho boa potência e controle no smash, especialmente para finalizar pontos.": 3,
    "meu smash é consistente e me permite definir pontos regularmente.": 4
}

# COMPOSICAO_JOGO: TROCA_BOLA_FUNDO_FOREHAND
mapa_forehand = {
    "erro frequentemente ou tenho dificuldade em acertar profundidade.": 1,
    "consigo manter trocas de bola, mas com pouca precisão.": 2,
    "tenho regularidade nos golpes de fundo, com boa direção e profundidade.": 3,
    "sou consistente e uso os golpes de fundo para construir jogadas estratégicas.": 4
}

# COMPOSICAO_JOGO: TROCA_BOLA_FUNDO_BACKHAND (mesmo padrão do forehand)
mapa_backhand = mapa_forehand

# COMPOSICAO_JOGO: DEVOLUCAO_SAQUE
mapa_devolucao = {
    "tenho dificuldade em devolver saques com controle.": 1,
    "consigo devolver, mas sem colocação ou efeito.": 2,
    "minhas devoluções são regulares e dificultam o próximo golpe do adversário.": 3,
    "sou capaz de devolver saques com precisão e iniciar o ponto em vantagem.": 4
}

# COMPOSICAO_JOGO: SAIDA_PAREDE_DEFESA
mapa_saida_defesa = {
    "tenho dificuldade em realizar a saída de parede com controle.": 1,
    "acerto saídas simples, mas sem muita profundidade.": 2,
    "sou consistente nas saídas de parede, com boa direção.": 3,
    "transformo saídas de parede em golpes estratégicos para atacar.": 4
}

# COMPOSICAO_JOGO: SAIDA_PAREDE_ATAQUE
mapa_saida_ataque = {
    "não utilizo essas jogadas no meu jogo.": 1,
    "tento usar, mas ainda erro frequentemente.": 2,
    "uso com consistência para preparar o ponto.": 3,
    "sou capaz de usar essas jogadas para pressionar e finalizar pontos.": 4
}

# COMPOSICAO_JOGO: MOVIMENTACAO
mapa_movimentacao = {
    "tenho dificuldade em me posicionar corretamente.": 1,
    "consigo me movimentar razoavelmente, mas perco algumas bolas.": 2,
    "tenho boa movimentação e me posiciono bem na maioria das jogadas.": 3,
    "tenho excelente movimentação e antecipo jogadas do adversário.": 4
}

# COMPOSICAO_JOGO: POSICIONAMENTO
mapa_posicionamento = {
    "tenho dificuldade em coordenar movimentos com o parceiro.": 1,
    "coordeno razoavelmente, mas ainda deixo buracos na defesa.": 2,
    "trabalho bem em dupla, cobrindo a quadra de forma eficiente.": 3,
    "tenho excelente entrosamento e crio jogadas estratégicas com o parceiro.": 4
}


In [14]:
# colunas ordinais simples, não importa a escala
# FAIXA_ETARIA
mapa_faixa = {
    "entre 15 e 17 anos": 1,
    "entre 18 e 21 anos": 2,
    "entre 22 e 35 anos": 3,
    "entre 36 e 45 anos": 4,
    "entre 46 e 55 anos": 5,
    "acima de 55 anos": 6
}

# TEMPO_PADEL
mapa_tempo = {
    "até 2 anos": 1,
    "entre 3 e 5 anos": 2,
    "entre 6 e 8 anos": 3,
    "entre 9 e 11 anos": 4,
    "mais de 11 anos": 5
}

# QUANTIDADE_TREINOS
mapa_treinos = {
    "não treino": 0,
    "1 vez por semana": 1,
    "2 vezes por semana": 2,
    "3 vezes por semana": 3,
    "mais de 3 vezes por semana": 4
}

# QUANTIDADE_JOGOS
mapa_jogos = mapa_treinos  # mesma lógica

# CATEGORIA_EM_TORNEIOS e AUTOAVALIACAO: CATEGORIA
mapa_categoria = {
    "iniciante": 1,
    "7ª categoria": 2,
    "6ª categoria": 3,
    "5ª categoria": 4,
    "4ª categoria": 5,
    "3ª categoria": 6,
    "2ª categoria": 7,
    "1ª categoria": 8
}

# QUALIDADE_CATEGORIA
mapa_qualidade = {
    "fraco": 1,
    "médio": 2,
    "forte": 3,
    "não sei": 0
}

# POSIÇÃO NA QUADRA
mapa_posicao_quadra = {
    "direita": 1,
    "esquerda": 2,
    "tanto faz": 3,
    "não sei ainda": 4
}

# DEFESA/ATAQUE NO JOGO
mapa_defesa_ataque = {
    "atacar": 1,
    "defender": 2,
    "ainda não sei": 3
}

# CONTROLE DE RITMO
mapa_controle_ritmo = {
    "sim": 1,
    "não": 2,
    "não sei responder": 3
}

# ESTILO DE DUPLAS
mapa_estilo_duplas = {
    "fixas": 1,
    "rotativas": 2,
    "não sei": 3
}

# FOCO / OBJETIVO
mapa_objetivo_foco = {
    "melhorar como jogador": 1,
    "praticar uma atividade fisica e socializar": 2,
    "socializar": 3,
    "competir": 4,
    "um pouco de todos": 5,
    "as três alternativas": 6,
    "todas alternativas": 7,
    "todos as opcoes acima": 8,
    "melhorar na parte técnica, avançado em categoria e competição": 9,
    "melhorar como jogador e socializar": 10,
    "as três primeiras opções em conjunto": 11,
    "socializar, fazer atividade fisica e melhorar como jogador": 12,
    "não sei": 13
}


In [15]:
# atribuindo os mapas a cada coluna
df["composicao_jogo: saque"] = df["composicao_jogo: saque"].map(mapa_saque)
df["composicao_jogo: usa_retoque"] = df["composicao_jogo: usa_retoque"].map(mapa_retoque)
df["composicao_jogo: voleio_ataque"] = df["composicao_jogo: voleio_ataque"].map(mapa_voleio_ataque)
df["composicao_jogo: voleio_defesa_contensao"] = df["composicao_jogo: voleio_defesa_contensao"].map(mapa_voleio_defesa)
df["composicao_jogo: bandeja_retomada_rede"] = df["composicao_jogo: bandeja_retomada_rede"].map(mapa_bandeja)
df["composicao_jogo: smash"] = df["composicao_jogo: smash"].map(mapa_smash)
df["composicao_jogo: troca_bola_fundo_forehand"] = df["composicao_jogo: troca_bola_fundo_forehand"].map(mapa_forehand)
df["composicao_jogo: troca_bola_fundo_backhand"] = df["composicao_jogo: troca_bola_fundo_backhand"].map(mapa_backhand)
df["composicao_jogo: devolucao_saque"] = df["composicao_jogo: devolucao_saque"].map(mapa_devolucao)  # invertido
df["composicao_jogo: saida_parede_defesa"] = df["composicao_jogo: saida_parede_defesa"].map(mapa_saida_defesa)  # espaço depois dos dois pontos
df["composicao_jogo: saida_parede_ataque"] = df["composicao_jogo: saida_parede_ataque"].map(mapa_saida_ataque)
df["composicao_jogo: movimentacao"] = df["composicao_jogo: movimentacao"].map(mapa_movimentacao)
df["composicao_jogo: posicionamento"] = df["composicao_jogo: posicionamento"].map(mapa_posicionamento)
df["dados_pessoais: faixa_etaria"] = df["dados_pessoais: faixa_etaria"].map(mapa_faixa)
df["experiencia: tempo_padel"] = df["experiencia: tempo_padel"].map(mapa_tempo)
df["experiencia: quantidade_treinos"] = df["experiencia: quantidade_treinos"].map(mapa_treinos)
df["autoavaliacao: categoria"] = df["autoavaliacao: categoria"].map(mapa_categoria)
df["autoavaliacao: qualidade_categoria"] = df["autoavaliacao: qualidade_categoria"].map(mapa_qualidade)
df["experiencia: quantidade_jogos"] = df["experiencia: quantidade_jogos"].map(mapa_jogos)
df["experiencia: categoria_em_torneios"] = df["experiencia: categoria_em_torneios"].map(mapa_categoria)
df['dados_pessoais: posicao_quadra'] = df['dados_pessoais: posicao_quadra'].map(mapa_posicao_quadra)
df['composicao_jogo: defesa_ataque'] = df['composicao_jogo: defesa_ataque'].map(mapa_defesa_ataque)
df['composicao_jog0: controle_ritmo'] = df['composicao_jog0: controle_ritmo'].map(mapa_controle_ritmo)
df['objetivo: estilo_duplas'] = df['objetivo: estilo_duplas'].map(mapa_estilo_duplas)
df['objetivo: foco'] = df['objetivo: foco'].map(mapa_objetivo_foco)


In [16]:
df['dados_pessoais: sexo'] = df['dados_pessoais: sexo'].map({'feminino': 0, 'masculino': 1})
df['experiencia: participa_torneios'] = df['experiencia: participa_torneios'].map({'não': 0, 'sim': 1})
df['dados_pessoais: autorizacao'] = df['dados_pessoais: autorizacao'].map({'não': 0, 'sim': 1})

In [17]:
print(df.columns)

Index(['dados_pessoais: nome', 'dados_pessoais: sexo',
       'dados_pessoais: faixa_etaria', 'dados_pessoais: posicao_quadra',
       'experiencia: tempo_padel', 'experiencia: quantidade_treinos',
       'experiencia: quantidade_jogos', 'experiencia: participa_torneios',
       'experiencia: categoria_em_torneios', 'habilidade_tecnica: saque',
       'habilidade_tecnica: voleio', 'habilidade_tecnica: smash',
       'habilidade_tecnica: movimentacao', 'composicao_jogo: defesa_ataque',
       'composicao_jog0: controle_ritmo', 'objetivo: estilo_duplas',
       'objetivo: foco', 'autoavaliacao: categoria',
       'autoavaliacao: qualidade_categoria', 'composicao_jogo: saque',
       'composicao_jogo: usa_retoque', 'composicao_jogo: voleio_ataque',
       'composicao_jogo: voleio_defesa_contensao',
       'composicao_jogo: bandeja_retomada_rede', 'composicao_jogo: smash',
       'composicao_jogo: troca_bola_fundo_forehand',
       'composicao_jogo: troca_bola_fundo_backhand',
       'comp

In [18]:
# Ver quantos valores faltantes por coluna
print(df.isna().sum())


dados_pessoais: nome                          0
dados_pessoais: sexo                          0
dados_pessoais: faixa_etaria                  0
dados_pessoais: posicao_quadra                0
experiencia: tempo_padel                      0
experiencia: quantidade_treinos               0
experiencia: quantidade_jogos                 0
experiencia: participa_torneios               0
experiencia: categoria_em_torneios            0
habilidade_tecnica: saque                     0
habilidade_tecnica: voleio                    0
habilidade_tecnica: smash                     0
habilidade_tecnica: movimentacao              0
composicao_jogo: defesa_ataque                0
composicao_jog0: controle_ritmo               0
objetivo: estilo_duplas                       0
objetivo: foco                                2
autoavaliacao: categoria                      0
autoavaliacao: qualidade_categoria            0
composicao_jogo: saque                        0
composicao_jogo: usa_retoque            

In [19]:
# Mostrar todas as colunas, mas apenas as primeiras 5 linhas
pd.set_option('display.max_columns', None)

# Exibe apenas as 5 primeiras linhas, mas todas as colunas
df.head()

dados_pessoais: nome  dados_pessoais: sexo  \
0               vanessa lopes                     0   
1          jose ariel machado                     1   
2      jociane bulegon samara                     0   
3  sabrina dalla costa saurim                     0   
4  patricia machado inchauspe                     0   

   dados_pessoais: faixa_etaria  dados_pessoais: posicao_quadra  \
0                             4                               1   
1                             4                               2   
2                             5                               2   
3                             4                               2   
4                             5                               1   

   experiencia: tempo_padel  experiencia: quantidade_treinos  \
0                         2                                0   
1                         2                                0   
2                         2                                1   
3                         1                                1   
4                         5                                0   

   experiencia: quantidade_jogos  experiencia: participa_torneios  \
0                              3                                1   
1                              3                                1   
2                              1                                1   
3                              2                                1   
4                              1                                1   

   experiencia: categoria_em_torneios  habilidade_tecnica: saque  \
0                                   5                          3   
1                                   7                          4   
2                                   5                          3   
3                                   5                          3   
4                                   5                          4   

   habilidade_tecnica: voleio  habilidade_tecnica: smash  \
0                           4                          3   
1                           4                          3   
2                           3                          2   
3                           3                          3   
4                           3                          3   

   habilidade_tecnica: movimentacao  composicao_jogo: defesa_ataque  \
0                                 4                               2   
1                                 3                               1   
2                                 3                               1   
3                                 3                               1   
4                                 4                               1   

   composicao_jog0: controle_ritmo  objetivo: estilo_duplas  objetivo: foco  \
0                                1                        2             1.0   
1                                1                        2             2.0   
2                                3                        2             1.0   
3                                1                        2             3.0   
4                                1                        1             3.0   

   autoavaliacao: categoria  autoavaliacao: qualidade_categoria  \
0                         5                                   2   
1                         7                                   2   
2                         5                                   2   
3                         5                                   1   
4                         5                                   2   

   composicao_jogo: saque  composicao_jogo: usa_retoque  \
0                       3                             2   
1                       3                             3   
2                       2                             2   
3                       2                             4   
4                       4                             2   

   composicao_jogo: voleio_ataque  composicao

In [20]:
#
#
#  TREINANDO O MODELO - UTILIZANDO RANDOM FOREST
#
#

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [22]:
# Colunas de entrada
X_cols = [
    'dados_pessoais: sexo',
    'dados_pessoais: faixa_etaria', 'dados_pessoais: posicao_quadra',
    'experiencia: tempo_padel', 'experiencia: quantidade_treinos',
    'experiencia: quantidade_jogos', 'experiencia: participa_torneios',
    'experiencia: categoria_em_torneios', 'habilidade_tecnica: saque',
    'habilidade_tecnica: voleio', 'habilidade_tecnica: smash',
    'habilidade_tecnica: movimentacao', 'composicao_jogo: defesa_ataque',
    'composicao_jog0: controle_ritmo', 'objetivo: estilo_duplas', 'composicao_jogo: saque',
    'composicao_jogo: usa_retoque', 'composicao_jogo: voleio_ataque',
    'composicao_jogo: voleio_defesa_contensao',
    'composicao_jogo: bandeja_retomada_rede', 'composicao_jogo: smash',
    'composicao_jogo: troca_bola_fundo_forehand',
    'composicao_jogo: troca_bola_fundo_backhand',
    'composicao_jogo: devolucao_saque',
    'composicao_jogo: saida_parede_defesa',
    'composicao_jogo: saida_parede_ataque', 'composicao_jogo: movimentacao',
    'composicao_jogo: posicionamento', 'dados_pessoais: autorizacao'
]

# Colunas de saída
y_cols = ['autoavaliacao: categoria']

X = df[X_cols]
y = df[y_cols]


In [23]:
print(X.isna().sum())




dados_pessoais: sexo                          0
dados_pessoais: faixa_etaria                  0
dados_pessoais: posicao_quadra                0
experiencia: tempo_padel                      0
experiencia: quantidade_treinos               0
experiencia: quantidade_jogos                 0
experiencia: participa_torneios               0
experiencia: categoria_em_torneios            0
habilidade_tecnica: saque                     0
habilidade_tecnica: voleio                    0
habilidade_tecnica: smash                     0
habilidade_tecnica: movimentacao              0
composicao_jogo: defesa_ataque                0
composicao_jog0: controle_ritmo               0
objetivo: estilo_duplas                       0
composicao_jogo: saque                        0
composicao_jogo: usa_retoque                  0
composicao_jogo: voleio_ataque                0
composicao_jogo: voleio_defesa_contensao      0
composicao_jogo: bandeja_retomada_rede        0
composicao_jogo: smash                  

In [24]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
X_res, y_res = ros.fit_resample(X, y)


In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)




In [26]:
rf = RandomForestClassifier(
    n_estimators=100,       # quantidade de árvores
    max_depth=None,         # profundidade máxima das árvores
    random_state=42
)

rf.fit(X_train, y_train)



/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(random_state=42)

In [27]:
y_pred = rf.predict(X_test)



In [28]:
print("Acurácia:", accuracy_score(y_test, y_pred))
print("\nRelatório de classificação:\n", classification_report(y_test, y_pred))
print("\nMatriz de Confusão:\n", confusion_matrix(y_test, y_pred))



Acurácia: 0.6666666666666666

Relatório de classificação:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00         1
           2       0.00      0.00      0.00         6
           3       0.45      0.83      0.59         6
           4       1.00      0.80      0.89         5
           5       0.78      0.88      0.82         8
           6       0.75      0.86      0.80         7
           7       0.50      0.50      0.50         2
           8       0.00      0.00      0.00         1

    accuracy                           0.67        36
   macro avg       0.56      0.61      0.58        36
weighted avg       0.59      0.67      0.62        36


Matriz de Confusão:
 [[1 0 0 0 0 0 0 0]
 [0 0 6 0 0 0 0 0]
 [0 1 5 0 0 0 0 0]
 [0 0 0 4 1 0 0 0]
 [0 0 0 0 7 1 0 0]
 [0 0 0 0 1 6 0 0]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 1 0]]


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [30]:
import pandas as pd
from collections import Counter
from imblearn.over_sampling import SMOTE

# --- 1. Detectar classes com apenas 1 amostra ---
contagem = Counter(y['autoavaliacao: categoria'])
classes_1_amostra = [cls for cls, cnt in contagem.items() if cnt == 1]
print("Classes com apenas 1 amostra:", classes_1_amostra)

# --- 2. Duplicar essas classes ---
for cls in classes_1_amostra:
    linha = df[df['autoavaliacao: categoria'] == cls]
    df = pd.concat([df, linha], ignore_index=True)

# Atualizar X e y
X = df[X_cols]
y = df[y_cols]

# k_neighbors deve ser menor que o número mínimo de amostras por classe
smote = SMOTE(random_state=42, k_neighbors=1)
X_res, y_res = smote.fit_resample(X, y.values.ravel())

# --- 4. Verificar a nova distribuição ---
print("Distribuição após SMOTE:", Counter(y_res))


Classes com apenas 1 amostra: []
Distribuição após SMOTE: Counter({np.int64(5): 49, np.int64(7): 49, np.int64(3): 49, np.int64(6): 49, np.int64(4): 49, np.int64(1): 49, np.int64(2): 49, np.int64(8): 49})


In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_res, y_res, test_size=0.2, random_state=42, stratify=y_res
)



In [32]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42, n_estimators=200)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)



In [33]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Acurácia:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred))


Acurácia: 0.8860759493670886
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         9
           3       0.83      1.00      0.91        10
           4       0.89      0.80      0.84        10
           5       0.67      0.80      0.73        10
           6       0.83      0.50      0.62        10
           7       0.91      1.00      0.95        10
           8       1.00      1.00      1.00        10

    accuracy                           0.89        79
   macro avg       0.89      0.89      0.88        79
weighted avg       0.89      0.89      0.88        79

Matriz de Confusão:
 [[10  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0]
 [ 0  0  2  8  0  0  0  0]
 [ 0  0  0  1  8  1  0  0]
 [ 0  0  0  0  4  5  1  0]
 [ 0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0 10]]
